name: Pull Request Blot
run-name: Pull Request Blot
on: 
    pull_request_target: 
        types: [opened, synchronize, reopened,labeled]
        paths: 'art/**'

jobs:
  echo-input:
    #if: contains(github.event.pull_request.labels.*.name, 'Submission') || contains(github.event.pull_request.labels.*.name, 'submission')
  
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4 # base (safe) branch because of pull_request_target
        with:
          path: ./ourhvcse
      - uses: actions/checkout@v4 # unsafe, user contributed branch
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ./theirhvcse

      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORPHEUS_PAT || secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./ourhvcse/.github/workflows/workflow.js')
            const { chdir } = require('node:process');
            chdir('./theirhvcse');
            console.log(await script({gh: github, ctx: context}))
